### ISSUE TITLE
Write Docstring BaseTimeSeriesMetrics  PRTS/prts/base/time_series_metrics.py 

### ISSUE THREAD

**Issue by ryoherisson** [CompML/PRTS#25]
## Summary
Write docstring in each function in BaseTimeSeriesMetrics.  

Format:
```
"""Description
  Args:
      args1: type
          Description
      args2: type
          Description
  Returns:
      type: Description
"""
```

## Goal
Write docstrings of BaseTImeSeriesMetrics  

## Todo
Write docstring of
- [ ] BaseTImeSeriesMetrics class
- [ ] __init__
- [ ] score
- [ ] _udf_gamma
- [ ] _gamma_select
- [ ] _gamma_function
- [ ] _compute_omega_reward
- [ ] _omega_function
- [ ] _delta_function
- [ ] _delta_select
- [ ] _udf_delta
- [ ] _shift
- [ ] _prepare_data

## Deadline
2020 / 12 / 30  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Example:
```
"""The function of selecting the gamma value according to the parameters.
  Args:
      gamma: str
          - 'one': the value 1
          - 'reciprocal';: a reciprocal of the overlap
          - 'udf_gamma': user defined gamma
      overlap: int
          overlap between real and pred
  Returns:
      float: the selected gamma
"""
```
