### ISSUE TITLE
Write Docstring TimeSeriesPrecision PRTS/prts/time_series_metrics/precision.py 

### ISSUE THREAD

**Issue by ryoherisson** [CompML/PRTS#26]
## Summary
Write docstring in each function in TimeSeriesPrecision.  

Format:
```
"""Description
  Args:
      args1: type
          Description
      args2: type
          Description
  Returns:
      type: Description
"""
```

## Goal
Write docstrings of TimeSeriesPrecision  

## Todo
Write docstring of
- [ ] TimeSeriesPrecision class
- [ ] __init__
- [ ] score
- [ ] _update_precision

## Deadline
2020 / 12 / 30  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Example:
```
"""The function of selecting the gamma value according to the parameters.
  Args:
      gamma: str
          - 'one': the value 1
          - 'reciprocal';: a reciprocal of the overlap
          - 'udf_gamma': user defined gamma
      overlap: int
          overlap between real and pred
  Returns:
      float: the selected gamma
"""
```
